### ISSUE TITLE
Can´t see transaction ID or number after installing custom order reference module

### ISSUE THREAD

**Issue by zyberland** [onpayio/prestashop#4]
Hi, 

We found a problem with showing the transaction id and number in the backoffice under orders area, after we installed the custom order reference module from prestacraft. http://prestacraft.com/custom-order-reference/

Does the Onpay module need the default order reference to find these details and show them in the backend?
Is there a way we can solve this problem when still using Custom Order Reference module?

**Comment by ebbesmoeller** [comment]
The module saves the UUID of the OnPay transaction in question, on the individual payments in the transaction_id field. This stored UUID is then used to fetch information about the OnPay transaction from the API.
Please see: https://github.com/onpayio/prestashop/blob/5011645afd9999d855e5f9aaac971a6a27b3dbf7/onpay.php#L301

**Comment by zyberland** [comment]
After uninstall of the module the onpay shows up again the transaction id without problem. 

We tried to add extra varianle to get the transaction number (4 digits) in the email sent for customer and admin. 
Actually we got it to work in customer email (order_conf), but it never showed op in admin email (new_order). 
Also the transaction id disappeared from the backend after adding extra code. 

Is there a way to get out the transaction number in email without destroy the other part of module?

**Comment by ebbesmoeller** [comment]
Clearly the module that is installed in pair with the OnPay module (or perhaps another module?), manipulates the transaction_id of the payment in question, and therefore the OnPay module is unable to fetch information about the transaction, and you won't be able to see any of the information supplied by OnPay.

**Comment by ebbesmoeller** [comment]
Closing the issue. Please file a new one, if you continue to experience problems.
