### ISSUE TITLE
The text "Pay with credit card" cannot be translated in back office

### ISSUE THREAD

**Issue by Scan-Drink** [onpayio/prestashop#5]
It is not possible to translate the text "Pay with credit card", which appears during payment at checkout.

**Comment by ebbesmoeller** [comment]
This has been resolved in the following PR https://github.com/onpayio/prestashop/pull/7
The proper strings for translations should now be available.

**Comment by ebbesmoeller** [comment]
A new release is ready with fixes: https://github.com/onpayio/prestashop/releases/tag/1.0.3
