### ISSUE TITLE
The payment window does not work a multi language shop

### ISSUE THREAD

**Issue by Scan-Drink** [onpayio/prestashop#6]
How to handle a multi language shop (eg. Danish / English)?

Payment window language appears to be locked by the "Payment window language" setting in the back office.
It would be more appropriate that language in the payment window was determined by the current language in the front office so that it follows the language chosen by the customer.

**Comment by ebbesmoeller** [comment]
A function has been added that allows for automatic determination of OnPay payment window language, based on currently selected language in frontoffice.
https://github.com/onpayio/prestashop/pull/7

**Comment by ebbesmoeller** [comment]
A new release is ready with fixes: https://github.com/onpayio/prestashop/releases/tag/1.0.3
